routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group([
    'prefix' => 'doctor-panel',
    'namespace' => 'Doctor',
    'as' => 'doctor.',
    'middleware' => ['auth', 'role:UNIVERSITY_DOCTOR'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')->name('index');

    Route::resource('items/{item}/authors', 'ItemAuthorController');
    Route::get('items/{item}/paid_transactions', 'PaidTransactionController@index')
        ->name('items.paid_transactions');
    Route::resource('items', 'ItemController');

    Route::resource('announcements', 'AnnouncementController');
});


Route::group([
    'prefix' => 'creator-student',
    'namespace' => 'CreatorStudent',
    'as' => 'creator-student.',
    'middleware' => ['auth', 'role:UNIVERSITY_CREATOR_STUDENT'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')->name('index');

    Route::resource('items/{item}/authors', 'ItemAuthorController');
    Route::get('items/{item}/paid_transactions', 'PaidTransactionController@index')
        ->name('items.paid_transactions');

    Route::resource('items', 'ItemController');
});


Route::group([
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'as' => 'dashboard.',
    'middleware' => ['auth', 'permission:access-dashboard'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')
        ->name('index');

    Route::resource('fields', 'FieldController');
    Route::get('levels', 'LevelController@index')
        ->name('levels.index');

    Route::resource('countries',
        'CountryController');
    Route::resource('countries/{country?}/governorates',
        'GovernorateController');
    Route::resource('countries/{country?}/governorates/{governorate?}/cities',
        'CityController');

    Route::get('json/countries', 'CountryController@jsonCountries')
        ->name('json.countries');
    Route::get('json/governorates', 'GovernorateController@jsonGovernorates')
        ->name('json.governorates');
    Route::get('json/cities', 'CityController@jsonCities')
        ->name('json.cities');

    Route::resource('universities',
        'UniversityController');
    Route::resource('universities/{university?}/faculties',
        'FacultyController');
    Route::resource('universities/{university?}/faculties/{faculty?}/majors',
        'MajorController');

    Route::get('json/universities', 'UniversityController@jsonUniversities')
        ->name('json.universities');
    Route::get('json/faculties', 'FacultyController@jsonFaculties')
        ->name('json.faculties');
    Route::get('json/majors', 'MajorController@jsonMajors')
        ->name('json.majors');

    Route::resource('universities/{university?}/faculties/{faculty?}/university-subjects',
        'UniversitySubjectController');
    //Route::resource('university-subjects', 'UniversitySubjectController');

    Route::get('json/university-subjects', 'UniversitySubjectController@jsonUniversitySubjects')
        ->name('json.university-subjects');

    Route::resource('school-subjects', 'SchoolSubjectController');

    Route::get('items/{item}/pdf', 'ItemController@viewPdf')
        ->name('items.viewPdf');
    Route::resource('items', 'ItemController');

    Route::resource('notifications', 'NotificationController')
        ->except(['show', 'edit', 'update', 'destroy']);

    Route::resource('charging-codes', 'ChargingCodeController');

    Route::get('charging-codes-files', 'ChargingCodesFileController@index')
        ->name('charging_codes_files.index');
    Route::get('charging-codes-files/{file}', 'ChargingCodesFileController@download')
        ->name('charging_codes_files.download');

    Route::get('users/export', 'UserController@export')
        ->name('users.export');
    Route::get('users/roles', 'UserController@roles')
        ->name('users.roles');
    Route::get('users/{user}/add-balance', 'UserController@addBalanceView')
        ->name('users.addBalanceView');
    Route::post('users/{user}/add-balance', 'UserController@addBalance')
        ->name('users.addBalance');
    Route::post('users/{user}/ban', 'UserController@ban')
        ->name('users.ban');
    Route::resource('users', 'UserController');
    Route::resource('doctors', 'DoctorController');

    Route::get('creator-students/requests', 'CreatorStudentController@requests')
        ->name('creator-students.requests');
    Route::get('creator-students/export', 'CreatorStudentController@export')
        ->name('creator-students.export');
    Route::resource('creator-students', 'CreatorStudentController');

    Route::resource('sys-users', 'SysUserController');

    Route::resource('rooms', 'RoomController');
    Route::get('rooms/{roomId}/requests/pending', 'RoomRequestController@pending')
        ->name('rooms.requests.pending');
    Route::get('rooms/{roomId}/requests/{requestId}/accept', 'RoomRequestController@accept')
        ->name('rooms.requests.accept');
    Route::get('rooms/{roomId}/requests/{requestId}/reject', 'RoomRequestController@reject')
        ->name('rooms.requests.reject');
    //Route::resource('conversations', 'ConversationController');

    Route::resource('banned-words', 'BannedWordController');

    Route::get('contact-us', 'ContactController@index')
        ->name('contact-us.index');
});


Auth::routes(['register' => false, 'verify' => true]);

Route::get('/home', 'HomeController@index')
    ->name('home');

app/Models/Announcement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Announcement extends Model
{
    protected $fillable = [
        'level',
        'text',
        'user_id',
        'faculty_id',
        'major_id',
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function faculty()
    {
        return $this->belongsTo('App\Models\Faculty');
    }

    public function major()
    {
        return $this->belongsTo('App\Models\Major');
    }

    public function attachments()
    {
        return $this->hasMany('App\Models\Attachment', 'related_to_id')
            ->where('related_to_model', '=', 'Announcement');
    }
}

app/Http/Controllers/Dashboard/DoctorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\DoctorStoreRequest;
use App\Http\Requests\Dashboard\DoctorUpdateRequest;
use App\Models\City;
use App\Models\Faculty;
use App\Models\University;
use App\Models\User;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;

class DoctorController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class, 'doctor');
    }

    public function index()
    {
        return view('dashboard.doctors.index')
            ->with('doctors', User::orderBy('id', 'DESC')->role('UNIVERSITY_DOCTOR')->paginate())
            ->with('total', User::role('UNIVERSITY_DOCTOR')->count())
            ->with('indexUrl', route('dashboard.doctors.index'));
    }

    public function create()
    {
        $cities = City::where(['country_id' => 1])->get();
        $universities = count($cities) > 0 ? University::where(['city_id' => $cities->first()->id])->get() : [];
        $faculties = count($universities) > 0 ? Faculty::where(['university_id' => $universities->first()->id])->get() : [];
        return view('dashboard.doctors.create')
            ->with('cities', $cities)
            ->with('universities', $universities)
            ->with('faculties', $faculties);
    }

    public function store(DoctorStoreRequest $request)
    {
        $doctor = User::create($request->validated());
        $role = Role::findByName('UNIVERSITY_DOCTOR');
        if ($role) {
            $doctor->syncRoles(['UNIVERSITY_DOCTOR']);
        }
        return redirect()->route('dashboard.doctors.index')
            ->with('message', trans('crud.success.store'))->with('class', 'alert-success');
    }

    public function show(User $doctor)
    {
        return redirect()->route('dashboard.doctors.edit', $doctor['id']);
    }

    public function edit(User $doctor)
    {
        $cities = City::where(['country_id' => 1])->get();
        $universities = count($cities) > 0 ? University::where(['city_id' => $doctor->city_id])->get() : [];
        $faculties = count($universities) > 0 ? Faculty::where(['university_id' => $doctor->university_id])->get() : [];
        return view('dashboard.doctors.edit')
            ->with('doctor', $doctor)
            ->with('cities', $cities)
            ->with('universities', $universities)
            ->with('faculties', $faculties);
    }

    public function update(DoctorUpdateRequest $request, User $doctor)
    {
        $data = $request->only(['city_id', 'university_id', 'name', 'email']);
        if ($request->has('password')) {
            $data['password'] = $request['password'];
        }
        if ($request->has('avatar')) {
            $data['avatar'] = $request['avatar'];
        }
        $doctor->update($data);
        return redirect()->route('dashboard.doctors.index')
            ->with('message', trans('crud.success.update'))->with('class', 'alert-success');
    }

    public function destroy(User $doctor)
    {
        $doctor->delete();
        return response()->json(['message' => 'Deleted Successfully'], 200);
    }
}

resources/views/doctor/announcements/create.blade.php
@extends('layouts.doctor-master')

@section('title','Create Announcement')

@section('content')
    <section class="section">
        <div class="section-header"><h1>Add Announcement</h1></div>
        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    @include('doctor.common._alert_message')
                    @include('doctor.common._alert_validation_errors')
                    <div class="card">
                        <div class="card-header">
                            <h4>Add a New Announcement</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('doctor.announcements.store') }}"
                                  enctype="multipart/form-data">
                                @csrf

                                {{-- Level --}}
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Level</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control @error('level') is-invalid @enderror"
                                                name="level" id="levels_list">
                                            @foreach($levels as $level)
                                                <option>{{$level->label}}</option>
                                            @endforeach
                                        </select>
                                        @error('level')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('level') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                {{-- Text --}}
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"
                                           for="text">Announcement</label>
                                    <div class="col-sm-12 col-md-7">
                                        <textarea class="form-control @error('text') is-invalid @enderror"
                                                  id="text" name="text" rows="4">{{old('text')}}</textarea>
                                        @error('text')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('text') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                {{-- Images --}}
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Images</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input class="form-control @error('images') is-invalid @enderror"
                                               type="file" name="images[]" multiple>
                                        @error('images')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('images') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                        <button type="submit" class="btn btn-primary">Add</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection

resources/views/doctor/announcements/edit.blade.php
@extends('layouts.doctor-master')

@section('title','Edit Announcement, '.$announcement->name)

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Edit Announcement</h1>
        </div>
        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    @include('doctor.common._alert_message')
                    <div class="card">
                        <div class="card-header">
                            <h4>Update Announcement</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('doctor.announcements.update',$announcement->id) }}"
                                  enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Level</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control @error('level') is-invalid @enderror"
                                                name="level">
                                            @foreach($levels as $level)
                                                <option {{$announcement->level==$level->label?' selected':''}}>{{$level->label}}</option>
                                            @endforeach
                                        </select>
                                        @error('level')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('level') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"
                                           for="text">Announcement</label>
                                    <div class="col-sm-12 col-md-7">
                                        <textarea class="form-control @error('text') is-invalid @enderror"
                                                  id="text" name="text"
                                                  rows="4">{{old('text',$announcement->text)}}</textarea>
                                        @error('text')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('text') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection

resources/views/doctor/announcements/index.blade.php
@extends('layouts.doctor-master')

@section('title','Manage Announcements')

@section('content')
    <section class="section">
        <div class="section-header"><h1>Manage Announcements</h1></div>
        @include('doctor.common._alert_message')
        <div class="section-body">
            @can('view-announcements')
                <div class="card">
                    <div class="card-header">
                        <h4>Announcements <span>({{ $total }})</span></h4>
                        <div class="card-header-action">
                            @can('create-announcements')
                                <a href="{{route('doctor.announcements.create')}}"
                                   class="btn btn-primary">Add <i class="fas fa-plus"></i></a>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="table-responsive table-invoice">
                            @if(count($announcements)>0)
                                <table class="table table-striped">
                                    <tbody>
                                    <tr>
                                        <th>Level</th>
                                        <th>Announcement</th>
                                        <th></th>
                                    </tr>
                                    @foreach($announcements as $announcement)
                                        <tr>
                                            <td>{{ $announcement->level }}</td>
                                            <td>{{ $announcement->text }}</td>
                                            <td class="text-right">
                                                @can('edit-announcements')
                                                    <a href="{{route('doctor.announcements.edit',$announcement->id)}}"
                                                       class="btn btn-primary">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                @endcan
                                                @can('delete-announcements')
                                                    <button class="btn btn-danger delete"
                                                            data-id="{{$announcement->id}}" type="button">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                @endcan
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @else
                                <div class="text-center p-3 text-muted">
                                    <h5>No Results</h5>
                                    <p>Looks like you have not added any announcements yet!</p>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
                @if(count($announcements)>0)
                    <div class="text-center">
                        {{$announcements->links()}}
                    </div>
                @endif
            @endcan
        </div>
    </section>
@endsection

@section('scripts')
    @include('doctor.common._modal_delete')
@endsection