routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group([
    'prefix' => 'doctor-panel',
    'namespace' => 'Doctor',
    'as' => 'doctor.',
    'middleware' => ['auth', 'role:UNIVERSITY_DOCTOR'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')->name('index');

    Route::resource('items/{item}/authors', 'ItemAuthorController');
    Route::get('items/{item}/paid_transactions', 'PaidTransactionController@index')
        ->name('items.paid_transactions');
    Route::resource('items', 'ItemController');

    Route::resource('announcements', 'AnnouncementController');
});


Route::group([
    'prefix' => 'creator-student',
    'namespace' => 'CreatorStudent',
    'as' => 'creator-student.',
    'middleware' => ['auth', 'role:UNIVERSITY_CREATOR_STUDENT'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')->name('index');

    Route::resource('items/{item}/authors', 'ItemAuthorController');
    Route::get('items/{item}/paid_transactions', 'PaidTransactionController@index')
        ->name('items.paid_transactions');

    Route::resource('items', 'ItemController');
});


Route::group([
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'as' => 'dashboard.',
    'middleware' => ['auth', 'permission:access-dashboard'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')
        ->name('index');

    Route::resource('fields', 'FieldController');
    Route::get('levels', 'LevelController@index')
        ->name('levels.index');

    Route::resource('countries',
        'CountryController');
    Route::resource('countries/{country?}/governorates',
        'GovernorateController');
    Route::resource('countries/{country?}/governorates/{governorate?}/cities',
        'CityController');

    Route::get('json/countries', 'CountryController@jsonCountries')
        ->name('json.countries');
    Route::get('json/governorates', 'GovernorateController@jsonGovernorates')
        ->name('json.governorates');
    Route::get('json/cities', 'CityController@jsonCities')
        ->name('json.cities');

    Route::resource('universities',
        'UniversityController');
    Route::resource('universities/{university?}/faculties',
        'FacultyController');
    Route::resource('universities/{university?}/faculties/{faculty?}/majors',
        'MajorController');

    Route::get('json/universities', 'UniversityController@jsonUniversities')
        ->name('json.universities');
    Route::get('json/faculties', 'FacultyController@jsonFaculties')
        ->name('json.faculties');
    Route::get('json/majors', 'MajorController@jsonMajors')
        ->name('json.majors');

    Route::resource('universities/{university?}/faculties/{faculty?}/university-subjects',
        'UniversitySubjectController');
    //Route::resource('university-subjects', 'UniversitySubjectController');

    Route::get('json/university-subjects', 'UniversitySubjectController@jsonUniversitySubjects')
        ->name('json.university-subjects');

    Route::resource('school-subjects', 'SchoolSubjectController');

    Route::get('items/{item}/pdf', 'ItemController@viewPdf')
        ->name('items.viewPdf');
    Route::resource('items', 'ItemController');

    Route::resource('notifications', 'NotificationController')
        ->except(['show', 'edit', 'update', 'destroy']);

    Route::resource('charging-codes', 'ChargingCodeController');

    Route::get('charging-codes-files', 'ChargingCodesFileController@index')
        ->name('charging_codes_files.index');
    Route::get('charging-codes-files/{file}', 'ChargingCodesFileController@download')
        ->name('charging_codes_files.download');

    Route::get('users/export', 'UserController@export')
        ->name('users.export');
    Route::get('users/roles', 'UserController@roles')
        ->name('users.roles');
    Route::get('users/{user}/add-balance', 'UserController@addBalanceView')
        ->name('users.addBalanceView');
    Route::post('users/{user}/add-balance', 'UserController@addBalance')
        ->name('users.addBalance');
    Route::post('users/{user}/ban', 'UserController@ban')
        ->name('users.ban');
    Route::resource('users', 'UserController');
    Route::resource('doctors', 'DoctorController');

    Route::get('creator-students/requests', 'CreatorStudentController@requests')
        ->name('creator-students.requests');
    Route::get('creator-students/export', 'CreatorStudentController@export')
        ->name('creator-students.export');
    Route::resource('creator-students', 'CreatorStudentController');

    Route::resource('sys-users', 'SysUserController');

    Route::resource('rooms', 'RoomController');
    Route::get('rooms/{roomId}/requests/pending', 'RoomRequestController@pending')
        ->name('rooms.requests.pending');
    Route::get('rooms/{roomId}/requests/{requestId}/accept', 'RoomRequestController@accept')
        ->name('rooms.requests.accept');
    Route::get('rooms/{roomId}/requests/{requestId}/reject', 'RoomRequestController@reject')
        ->name('rooms.requests.reject');
    //Route::resource('conversations', 'ConversationController');

    Route::resource('banned-words', 'BannedWordController');

    Route::get('contact-us', 'ContactController@index')
        ->name('contact-us.index');
});


Auth::routes(['register' => false, 'verify' => true]);

Route::get('/home', 'HomeController@index')
    ->name('home');

app/Http/Controllers/Dashboard/CreatorStudentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\CreatorStudentStoreRequest;
use App\Http\Requests\Dashboard\CreatorStudentUpdateRequest;
use App\Models\City;
use App\Models\CreatorStudentRequest;
use App\Models\Faculty;
use App\Models\Governorate;
use App\Models\University;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\CreatorStudentsExport;

class CreatorStudentController extends Controller
{
    public function requests()
    {
        return view('dashboard.creator-students.requests')
            ->with('creatorStudentRequests', CreatorStudentRequest::where('status', 'PENDING')
                ->orderBy('id', 'desc')->paginate())
            ->with('total', CreatorStudentRequest::where('status', 'PENDING')->count());
    }

    public function index(Request $request)
    {
        $search_q = '';
        if ($request->has('search_q')) {
            $search_q = $request['search_q'];
        }

        $where = [];
        if ($request->has('majorId')) {
            $where['major_id'] = $request['majorId'];
        }
        if ($request->has('facultyId')) {
            $where['faculty_id'] = $request['facultyId'];
        }
        if ($request->has('universityId')) {
            $where['university_id'] = $request['universityId'];
        }
        if ($request->has('governorateId')) {
            $where['governorate_id'] = $request['governorateId'];
        }
        $creatorStudents = User::role('UNIVERSITY_CREATOR_STUDENT')
            ->where($where)
            ->where('name', 'LIKE', '%' . $search_q . '%')
            ->orderBy('id', 'DESC')
            ->paginate();

        return view('dashboard.creator-students.index')
            ->with('creatorStudents', $creatorStudents)
            ->with('total', $creatorStudents->total())
            ->with('indexUrl', route('dashboard.creator-students.index'));
    }

    public function export(Request $request)
    {
        $fileName = 'creatorstudents' . time();
        return Excel::download(new CreatorStudentsExport($this->buildingWhereQuery($request->all())), $fileName . '.xlsx');
    }

    private function buildingWhereQuery($dataArray)
    {
        $where = [];
        if (array_key_exists('majorId', $dataArray)) {
            $where['major_id'] = $dataArray['majorId'];
        }
        if (array_key_exists('facultyId', $dataArray)) {
            $where['faculty_id'] = $dataArray['facultyId'];
        }
        if (array_key_exists('universityId', $dataArray)) {
            $where['university_id'] = $dataArray['universityId'];
        }
        if (array_key_exists('governorateId', $dataArray)) {
            $where['governorate_id'] = $dataArray['governorateId'];
        }
        return $where;
    }

    public function create()
    {
        $governorates = Governorate::where(['country_id' => 1])->get();
        $universities = count($governorates) > 0 ? University::where(['governorate_id' => $governorates->first()->id])->get() : [];
        $faculties = count($universities) > 0 ? Faculty::where(['university_id' => $universities->first()->id])->get() : [];
        return view('dashboard.creator-students.create')
            ->with('governorates', $governorates)
            ->with('universities', $universities)
            ->with('faculties', $faculties);
    }

    public function store(CreatorStudentStoreRequest $request)
    {
        $creatorStudent = User::create($request->validated());
        $role = Role::findByName('UNIVERSITY_CREATOR_STUDENT');
        if ($role) {
            $creatorStudent->syncRoles(['UNIVERSITY_CREATOR_STUDENT']);
        }
        return redirect()->route('dashboard.creator-students.index')
            ->with('message', trans('crud.success.store'))->with('class', 'alert-success');
    }

    public function show(User $creatorStudent)
    {
        return redirect()->route('dashboard.creator-students.edit', $creatorStudent['id']);
    }

    public function edit(User $creatorStudent)
    {
        $cities = City::where(['country_id' => 1])->get();
        $universities = count($cities) > 0 ? University::where(['city_id' => $creatorStudent->city_id])->get() : [];
        $faculties = count($universities) > 0 ? Faculty::where(['university_id' => $creatorStudent->university_id])->get() : [];
        return view('dashboard.creator-students.edit')
            ->with('creatorStudent', $creatorStudent)
            ->with('cities', $cities)
            ->with('universities', $universities)
            ->with('faculties', $faculties);
    }

    public function update(CreatorStudentUpdateRequest $request, User $creatorStudent)
    {
        $data = $request->only(['city_id', 'university_id', 'name', 'email']);
        if ($request->has('password')) {
            $data['password'] = $request['password'];
        }
        $creatorStudent->update($data);
        return redirect()->route('dashboard.creator-students.index')
            ->with('message', trans('crud.success.update'))->with('class', 'alert-success');
    }

    public function destroy(User $creatorStudent)
    {
        $creatorStudent->delete();
        return response()->json(['message' => 'Deleted Successfully'], 200);
    }
}

resources/views/creator-student/common/_ajax_hydrateList.blade.php
<script>
    function hydrateList(countryId) {
        $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
        $.ajax({
            type: "GET",
            data: {countryId: countryId},
            url: '{{route('dashboard.json.cities')}}',
            dataType: 'json',
            success: function(data) {
                const $el = $("#cities_list");
                $el.empty(); // remove old options
                $.each(data, function(value, key) {
                    $el.append($("<option></option>").attr("value", key.id).text(key.name));
                });
            }
        });
    }
</script>

resources/views/creator-student/common/_alert_message.blade.php
@if(session('message'))
    <div class="alert {{ session('class') }} alert-dismissible show fade">
        <div class="alert-body">
            <button class="close" data-dismiss="alert"><span>×</span></button>
            {{ session('message') }}
        </div>
    </div>
@endif

resources/views/creator-student/common/_alert_validation_errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/creator-student/common/_modal_delete.blade.php
{{--
-- Created by: @MoWagdy
-- this file needs (id), (url),
--}}

{{--<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>--}}
<script src="{{asset('assets/dashboard/js/sweetalert/sweetalert.min.js')}}"></script>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $(document).on('click', '.delete', function (e) {
        const id = $(this).data('id');
        console.log(id);

        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover these data!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        url: "{{$indexUrl}}" + '/' + id,
                        type: "POST",
                        data: {'_method': 'DELETE'},
                        success: () => {
                            swal({
                                title: "Success!",
                                text: "Post has been deleted \n Click OK to refresh the page",
                                icon: "success",
                            });
                            location.reload();
                        },
                        error: () => {
                            swal({
                                title: 'Opps...',
                                //text : data.message,
                                icon: 'error',
                                //timer: '1500'
                            })
                        }
                    })
                } else {
                    swal("Your imaginary file is safe!");
                }
            });
    });
</script>