routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group([
    'prefix' => 'doctor-panel',
    'namespace' => 'Doctor',
    'as' => 'doctor.',
    'middleware' => ['auth', 'role:UNIVERSITY_DOCTOR'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')->name('index');

    Route::resource('items/{item}/authors', 'ItemAuthorController');
    Route::get('items/{item}/paid_transactions', 'PaidTransactionController@index')
        ->name('items.paid_transactions');
    Route::resource('items', 'ItemController');

    Route::resource('announcements', 'AnnouncementController');
});


Route::group([
    'prefix' => 'creator-student',
    'namespace' => 'CreatorStudent',
    'as' => 'creator-student.',
    'middleware' => ['auth', 'role:UNIVERSITY_CREATOR_STUDENT'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')->name('index');

    Route::resource('items/{item}/authors', 'ItemAuthorController');
    Route::get('items/{item}/paid_transactions', 'PaidTransactionController@index')
        ->name('items.paid_transactions');

    Route::resource('items', 'ItemController');
});


Route::group([
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'as' => 'dashboard.',
    'middleware' => ['auth', 'permission:access-dashboard'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')
        ->name('index');

    Route::resource('fields', 'FieldController');
    Route::get('levels', 'LevelController@index')
        ->name('levels.index');

    Route::resource('countries',
        'CountryController');
    Route::resource('countries/{country?}/governorates',
        'GovernorateController');
    Route::resource('countries/{country?}/governorates/{governorate?}/cities',
        'CityController');

    Route::get('json/countries', 'CountryController@jsonCountries')
        ->name('json.countries');
    Route::get('json/governorates', 'GovernorateController@jsonGovernorates')
        ->name('json.governorates');
    Route::get('json/cities', 'CityController@jsonCities')
        ->name('json.cities');

    Route::resource('universities',
        'UniversityController');
    Route::resource('universities/{university?}/faculties',
        'FacultyController');
    Route::resource('universities/{university?}/faculties/{faculty?}/majors',
        'MajorController');

    Route::get('json/universities', 'UniversityController@jsonUniversities')
        ->name('json.universities');
    Route::get('json/faculties', 'FacultyController@jsonFaculties')
        ->name('json.faculties');
    Route::get('json/majors', 'MajorController@jsonMajors')
        ->name('json.majors');

    Route::resource('universities/{university?}/faculties/{faculty?}/university-subjects',
        'UniversitySubjectController');
    //Route::resource('university-subjects', 'UniversitySubjectController');

    Route::get('json/university-subjects', 'UniversitySubjectController@jsonUniversitySubjects')
        ->name('json.university-subjects');

    Route::resource('school-subjects', 'SchoolSubjectController');

    Route::get('items/{item}/pdf', 'ItemController@viewPdf')
        ->name('items.viewPdf');
    Route::resource('items', 'ItemController');

    Route::resource('notifications', 'NotificationController')
        ->except(['show', 'edit', 'update', 'destroy']);

    Route::resource('charging-codes', 'ChargingCodeController');

    Route::get('charging-codes-files', 'ChargingCodesFileController@index')
        ->name('charging_codes_files.index');
    Route::get('charging-codes-files/{file}', 'ChargingCodesFileController@download')
        ->name('charging_codes_files.download');

    Route::get('users/export', 'UserController@export')
        ->name('users.export');
    Route::get('users/roles', 'UserController@roles')
        ->name('users.roles');
    Route::get('users/{user}/add-balance', 'UserController@addBalanceView')
        ->name('users.addBalanceView');
    Route::post('users/{user}/add-balance', 'UserController@addBalance')
        ->name('users.addBalance');
    Route::post('users/{user}/ban', 'UserController@ban')
        ->name('users.ban');
    Route::resource('users', 'UserController');
    Route::resource('doctors', 'DoctorController');

    Route::get('creator-students/requests', 'CreatorStudentController@requests')
        ->name('creator-students.requests');
    Route::get('creator-students/export', 'CreatorStudentController@export')
        ->name('creator-students.export');
    Route::resource('creator-students', 'CreatorStudentController');

    Route::resource('sys-users', 'SysUserController');

    Route::resource('rooms', 'RoomController');
    Route::get('rooms/{roomId}/requests/pending', 'RoomRequestController@pending')
        ->name('rooms.requests.pending');
    Route::get('rooms/{roomId}/requests/{requestId}/accept', 'RoomRequestController@accept')
        ->name('rooms.requests.accept');
    Route::get('rooms/{roomId}/requests/{requestId}/reject', 'RoomRequestController@reject')
        ->name('rooms.requests.reject');
    //Route::resource('conversations', 'ConversationController');

    Route::resource('banned-words', 'BannedWordController');

    Route::get('contact-us', 'ContactController@index')
        ->name('contact-us.index');
});


Auth::routes(['register' => false, 'verify' => true]);

Route::get('/home', 'HomeController@index')
    ->name('home');

app/Http/Controllers/Dashboard/BannedWordController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\BannedWordStoreRequest;
use App\Http\Requests\Dashboard\BannedWordUpdateRequest;
use App\Models\BannedWord;
use App\Http\Controllers\Controller;

class BannedWordController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(BannedWord::class, 'banned_word');
    }

    public function index()
    {
        return view('dashboard.banned-words.index')
            ->with('bannedWords', BannedWord::orderBy('id', 'desc')->paginate())
            ->with('total', BannedWord::count())
            ->with('indexUrl', route('dashboard.banned-words.index'));
    }

    public function create()
    {
        return view('dashboard.banned-words.create');
    }

    public function store(BannedWordStoreRequest $request)
    {
        BannedWord::create($request->validated());
        return redirect()->route('dashboard.banned-words.index')
            ->with('message', trans('crud.success.store'))->with('class', 'alert-success');
    }

    public function show(BannedWord $bannedWord)
    {
        return redirect()->route('dashboard.banned-words.edit', $bannedWord['id']);
    }

    public function edit(BannedWord $bannedWord)
    {
        return view('dashboard.banned-words.edit')
            ->with('bannedWord', $bannedWord);
    }

    public function update(BannedWordUpdateRequest $request, BannedWord $bannedWord)
    {
        $bannedWord->update($request->validated());
        return redirect()->route('dashboard.banned-words.index')
            ->with('message', trans('crud.success.update'))->with('class', 'alert-success');
    }

    public function destroy(BannedWord $bannedWord)
    {
        $bannedWord->delete();
        return redirect()->route('dashboard.banned-words.index')
            ->with('message', trans('crud.success.delete'))->with('class', 'alert-success');
    }
}

app/Http/Controllers/Dashboard/ChargingCodeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\ChargingCodeStoreRequest;
use App\Http\Requests\Dashboard\ChargingCodeUpdateRequest;
use App\Models\ChargingCode;
use App\Traits\MoneyOperations\ChargingCodesFileTrait;
use App\Http\Controllers\Controller;

class ChargingCodeController extends Controller
{
    use ChargingCodesFileTrait;

    public function __construct()
    {
        $this->authorizeResource(ChargingCode::class, 'charging_code');
    }

    public function index()
    {
        return view('dashboard.charging-codes.index')
            ->with('chargingCodes', ChargingCode::orderBy('id', 'desc')->paginate())
            ->with('total', ChargingCode::count())
            ->with('indexUrl', route('dashboard.charging-codes.index'));
    }

    public function create()
    {
        return view('dashboard.charging-codes.create');
    }

    public function store(ChargingCodeStoreRequest $request)
    {
        $fileContent = '';
        for ($i = 0; $i < $request['count']; $i++) {

            $chargingCode = ChargingCode::create([
                'expires_at' => $request['expires_at'],
                'money' => $request['money'],
            ]);
            $fileContent .= $chargingCode->code . "\r\n";
        }

        $this->storeNewFile($fileContent, $request['count'], $request['money'], $request['expires_at']);

        return redirect()->route('dashboard.charging-codes.index')
            ->with('message', $request['count'] . ' generated successfully')->with('class', 'alert-success');
    }

    public function show(ChargingCode $chargingCode)
    {
        return redirect()->route('dashboard.charging-codes.edit', $chargingCode['id']);
    }

    public function edit(ChargingCode $chargingCode)
    {
        return view('dashboard.charging-codes.edit')
            ->with('chargingCode', $chargingCode);
    }

    public function update(ChargingCodeUpdateRequest $request, ChargingCode $chargingCode)
    {
        $chargingCode->update($request->validated());
        return redirect()->route('dashboard.charging-codes.index')
            ->with('message', 'charging Code updated successfully')->with('class', 'alert-success');
    }

    public function destroy(ChargingCode $chargingCode)
    {
        try {
            $chargingCode->delete();
            return response()->json(['message' => 'Deleted Successfully'], 200);
        } catch (\Exception $exception) {
            return response()->json(['message' => $exception], 400);
        }
    }

}

app/Http/Controllers/Dashboard/ChargingCodesFileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Traits\MoneyOperations\ChargingCodesFileTrait;
use App\Http\Controllers\Controller;

class ChargingCodesFileController extends Controller
{
    use ChargingCodesFileTrait;
}

app/Http/Controllers/Dashboard/CityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\CityStoreRequest;
use App\Http\Requests\Dashboard\CityUpdateRequest;
use App\Models\City;
use App\Http\Controllers\Controller;
use App\Models\Country;
use App\Models\Governorate;
use Illuminate\Http\Request;

class CityController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(City::class, 'city');
    }

    public function index(Country $country, Governorate $governorate)
    {
        return view('dashboard.cities.index')
            ->with('country', $country)
            ->with('governorate', $governorate)
            ->with('cities', City::where([
                'country_id' => $country->id, 'governorate_id' => $governorate->id
            ])->orderBy('id', 'desc')->paginate())
            ->with('total', City::where([
                'country_id' => $country->id, 'governorate_id' => $governorate->id
            ])->count())
            ->with('indexUrl', route('dashboard.cities.index'));
    }

    public function jsonCities(Request $request)
    {
        if ($request->has('countryId')) {
            return response()->json(City::where('country_id', $request['countryId'])->get());
        }
        return response()->json(City::all());
    }

    public function create(Country $country, Governorate $governorate)
    {
        return view('dashboard.cities.create')
            ->with('country', $country)
            ->with('governorate', $governorate);
    }

    public function store(Country $country, Governorate $governorate, CityStoreRequest $request)
    {
        $data = $request->validated();
        $data['country_id'] = $country->id;
        $data['governorate_id'] = $governorate->id;
        City::create($data);
        return redirect()->route('dashboard.cities.index', [
            'country' => $country->id, 'governorate' => $governorate->id
        ])->with('message', trans('crud.success.store'))->with('class', 'alert-success');
    }

    public function show(Country $country, Governorate $governorate, City $city)
    {
        return redirect()
            ->route('dashboard.cities.edit', [
                'country' => $country->id,
                'governorate' => $governorate->id,
                'city' => $city['id'],
            ]);
    }

    public function edit(Country $country, Governorate $governorate, City $city)
    {
        return view('dashboard.cities.edit')
            ->with('country', $country)
            ->with('governorate', $governorate)
            ->with('city', $city);
    }

    public function update(Country $country, Governorate $governorate, CityUpdateRequest $request, City $city)
    {
        $city->update($request->validated());
        return redirect()->route('dashboard.cities.index', [
            'country' => $country->id, 'governorate' => $governorate->id,
        ])->with('message', trans('crud.success.update'))->with('class', 'alert-success');
    }

    public function destroy(Country $country, Governorate $governorate, City $city)
    {
        $city->delete();
        return redirect()->route('dashboard.cities.index')
            ->with('message', trans('crud.success.delete'))->with('class', 'alert-success');
    }
}

app/Http/Controllers/Dashboard/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Contact;

class ContactController extends Controller
{
    public function index()
    {
        return view('dashboard.contacts.index')
            ->with('messages', Contact::where(['seen' => false])->orderBy('id', 'desc')->paginate())
            ->with('total', Contact::where(['seen' => false])->count());
    }
}

app/Http/Controllers/Dashboard/CountryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\CountryStoreRequest;
use App\Http\Requests\Dashboard\CountryUpdateRequest;
use App\Models\Country;
use App\Http\Controllers\Controller;

class CountryController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Country::class, 'country');
    }

    public function index()
    {
        return view('dashboard.countries.index')
            ->with('countries', Country::orderBy('id', 'desc')->paginate())
            ->with('total', Country::count())
            ->with('indexUrl', route('dashboard.countries.index'));
    }

    public function jsonCountries()
    {
        return response()->json(Country::all());
    }

    public function create()
    {
        return view('dashboard.countries.create');
    }

    public function store(CountryStoreRequest $request)
    {
        Country::create($request->validated());
        return redirect()->route('dashboard.countries.index')
            ->with('message', trans('crud.success.store'))->with('class', 'alert-success');
    }

    public function show(Country $country)
    {
        return redirect()->route('dashboard.countries.edit', $country['id']);
    }

    public function edit(Country $country)
    {
        return view('dashboard.countries.edit')
            ->with('country', $country);
    }

    public function update(CountryUpdateRequest $request, Country $country)
    {
        $country->update($request->validated());
        return redirect()->route('dashboard.countries.index')
            ->with('message', trans('crud.success.update'))->with('class', 'alert-success');
    }

    public function destroy(Country $country)
    {
        $country->delete();
        return redirect()->route('dashboard.countries.index')
            ->with('message', trans('crud.success.delete'))->with('class', 'alert-success');
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }
}

app/Http/Controllers/Dashboard/LevelController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Level;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LevelController extends Controller
{
    public function index(Request $request)
    {
        if ($request->has('type')) {
            return response()->json(Level::where('type', $request['type'])->get());
        }
        return response()->json(Level::all());
    }
}

resources/views/dashboard/fields/create.blade.php
@extends('layouts.dashboard-master')

@section('title','Create Field')

@section('content')
    <section class="section">
        <div class="section-header"><h1>Add Field</h1></div>
        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    @include('dashboard.common._alert_message')
                    <div class="card">
                        <div class="card-header">
                            <h4>Add a New Field</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('dashboard.fields.store') }}"
                                  enctype="multipart/form-data">
                                @csrf
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Field Label</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" name="label" value="{{old('label')}}"
                                               class="form-control @error('label') is-invalid @enderror">
                                        @error('label')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('label') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                         <button type="submit" class="btn btn-primary">Add</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection

resources/views/dashboard/fields/edit.blade.php
@extends('layouts.dashboard-master')

@section('title','Edit Field, '.$field->name)

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Edit Field</h1>
        </div>
        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    @include('dashboard.common._alert_message')
                    <div class="card">
                        <div class="card-header">
                            <h4>Update Field</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('dashboard.fields.update',$field->id) }}"
                                  enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Field Label</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" name="label" value="{{old('label',$field->label)}}"
                                               class="form-control @error('label') is-invalid @enderror">
                                        @error('label')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('label') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection

resources/views/dashboard/fields/index.blade.php
@extends('layouts.dashboard-master')

@section('title','Manage Fields')

@section('content')
    <section class="section">
        <div class="section-header"><h1>Manage Fields</h1></div>
        @include('dashboard.common._alert_message')
        <div class="section-body">
            @can('view-fields')
                <div class="card">
                    <div class="card-header">
                        <h4>Fields <span>({{ $total }})</span></h4>
                        <div class="card-header-action">
                            @can('create-fields')
                                <a href="{{route('dashboard.fields.create')}}"
                                   class="btn btn-primary">Add <i class="fas fa-plus"></i></a>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="table-responsive table-invoice">
                            @if(count($fields)>0)
                                <table class="table table-striped">
                                    <tbody>
                                    <tr>
                                        <th>Label</th>

                                        <th></th>
                                    </tr>
                                    @foreach($fields as $field)
                                        <tr>
                                            <td>{{ $field->label }}</td>
                                            <td class="text-right">
                                                @can('edit-fields')
                                                    <a href="{{route('dashboard.fields.edit',$field->id)}}"
                                                       class="btn btn-primary">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                @endcan
                                                @can('delete-fields')
                                                    <button class="btn btn-danger delete"
                                                            data-id="{{$field->id}}" type="button">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                @endcan
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @else
                                <div class="text-center p-3 text-muted">
                                    <h5>No Results</h5>
                                    <p>Looks like you have not added any fields yet!</p>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
                @if(count($fields)>0)
                    <div class="text-center">
                        {{$fields->links()}}
                    </div>
                @endif
            @endcan
        </div>
    </section>
@endsection

@section('scripts')
    @include('dashboard.common._modal_delete')
@endsection