routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group([
    'prefix' => 'doctor-panel',
    'namespace' => 'Doctor',
    'as' => 'doctor.',
    'middleware' => ['auth', 'role:UNIVERSITY_DOCTOR'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')->name('index');

    Route::resource('items/{item}/authors', 'ItemAuthorController');
    Route::get('items/{item}/paid_transactions', 'PaidTransactionController@index')
        ->name('items.paid_transactions');
    Route::resource('items', 'ItemController');

    Route::resource('announcements', 'AnnouncementController');
});


Route::group([
    'prefix' => 'creator-student',
    'namespace' => 'CreatorStudent',
    'as' => 'creator-student.',
    'middleware' => ['auth', 'role:UNIVERSITY_CREATOR_STUDENT'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')->name('index');

    Route::resource('items/{item}/authors', 'ItemAuthorController');
    Route::get('items/{item}/paid_transactions', 'PaidTransactionController@index')
        ->name('items.paid_transactions');

    Route::resource('items', 'ItemController');
});


Route::group([
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'as' => 'dashboard.',
    'middleware' => ['auth', 'permission:access-dashboard'],
], function () {
    Route::get('/', 'HomeController@index');
    Route::get('index', 'HomeController@index')
        ->name('index');

    Route::resource('fields', 'FieldController');
    Route::get('levels', 'LevelController@index')
        ->name('levels.index');

    Route::resource('countries',
        'CountryController');
    Route::resource('countries/{country?}/governorates',
        'GovernorateController');
    Route::resource('countries/{country?}/governorates/{governorate?}/cities',
        'CityController');

    Route::get('json/countries', 'CountryController@jsonCountries')
        ->name('json.countries');
    Route::get('json/governorates', 'GovernorateController@jsonGovernorates')
        ->name('json.governorates');
    Route::get('json/cities', 'CityController@jsonCities')
        ->name('json.cities');

    Route::resource('universities',
        'UniversityController');
    Route::resource('universities/{university?}/faculties',
        'FacultyController');
    Route::resource('universities/{university?}/faculties/{faculty?}/majors',
        'MajorController');

    Route::get('json/universities', 'UniversityController@jsonUniversities')
        ->name('json.universities');
    Route::get('json/faculties', 'FacultyController@jsonFaculties')
        ->name('json.faculties');
    Route::get('json/majors', 'MajorController@jsonMajors')
        ->name('json.majors');

    Route::resource('universities/{university?}/faculties/{faculty?}/university-subjects',
        'UniversitySubjectController');
    //Route::resource('university-subjects', 'UniversitySubjectController');

    Route::get('json/university-subjects', 'UniversitySubjectController@jsonUniversitySubjects')
        ->name('json.university-subjects');

    Route::resource('school-subjects', 'SchoolSubjectController');

    Route::get('items/{item}/pdf', 'ItemController@viewPdf')
        ->name('items.viewPdf');
    Route::resource('items', 'ItemController');

    Route::resource('notifications', 'NotificationController')
        ->except(['show', 'edit', 'update', 'destroy']);

    Route::resource('charging-codes', 'ChargingCodeController');

    Route::get('charging-codes-files', 'ChargingCodesFileController@index')
        ->name('charging_codes_files.index');
    Route::get('charging-codes-files/{file}', 'ChargingCodesFileController@download')
        ->name('charging_codes_files.download');

    Route::get('users/export', 'UserController@export')
        ->name('users.export');
    Route::get('users/roles', 'UserController@roles')
        ->name('users.roles');
    Route::get('users/{user}/add-balance', 'UserController@addBalanceView')
        ->name('users.addBalanceView');
    Route::post('users/{user}/add-balance', 'UserController@addBalance')
        ->name('users.addBalance');
    Route::post('users/{user}/ban', 'UserController@ban')
        ->name('users.ban');
    Route::resource('users', 'UserController');
    Route::resource('doctors', 'DoctorController');

    Route::get('creator-students/requests', 'CreatorStudentController@requests')
        ->name('creator-students.requests');
    Route::get('creator-students/export', 'CreatorStudentController@export')
        ->name('creator-students.export');
    Route::resource('creator-students', 'CreatorStudentController');

    Route::resource('sys-users', 'SysUserController');

    Route::resource('rooms', 'RoomController');
    Route::get('rooms/{roomId}/requests/pending', 'RoomRequestController@pending')
        ->name('rooms.requests.pending');
    Route::get('rooms/{roomId}/requests/{requestId}/accept', 'RoomRequestController@accept')
        ->name('rooms.requests.accept');
    Route::get('rooms/{roomId}/requests/{requestId}/reject', 'RoomRequestController@reject')
        ->name('rooms.requests.reject');
    //Route::resource('conversations', 'ConversationController');

    Route::resource('banned-words', 'BannedWordController');

    Route::get('contact-us', 'ContactController@index')
        ->name('contact-us.index');
});


Auth::routes(['register' => false, 'verify' => true]);

Route::get('/home', 'HomeController@index')
    ->name('home');

app/Http/Controllers/Api/ItemController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\Api\ItemBuyCallbackRequest;
use App\Http\Requests\Api\ItemBuyRequest;
use App\Http\Requests\Api\ItemUploadRequest;
use App\Models\Item;
use App\Models\UserBoughtItem;
use App\Models\Transaction;
use App\Traits\MoneyOperations\MoneyChargerTrait;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\ItemsCollection;
use App\Http\Resources\Item as ItemResource;

class ItemController extends Controller
{
    use MoneyChargerTrait;

    public function index(Request $request)
    {
        $where = ['status' => 'APPROVED'];
        if ($request->has('type')) {
            $where['type'] = $request['type'];
        }
        if ($request->has('level')) {
            $where['level'] = $request['level'];
        }
        if ($request->has('school_subject_id')) {
            $where['school_subject_id'] = $request['school_subject_id'];
        }
        if ($request->has('university_subject_id')) {
            $where['university_subject_id'] = $request['university_subject_id'];
        }

        $whereHasUniSubject = [];
        if ($request->has('faculty_id')) {
            $whereHasUniSubject['faculty_id'] = $request['faculty_id'];
        }
        if ($request->has('major_id')) {
            $whereHasUniSubject['major_id'] = $request['major_id'];
        }

        if ($request->has('name')) {
            return new ItemsCollection(Item::where($where)
                ->where('name', 'like', '%' . $request['name'] . '%')
                ->whereHas('universitySubject', function ($q) use ($whereHasUniSubject) {
                    $q->where($whereHasUniSubject);
                })
                ->paginate());
        } else {
            return new ItemsCollection(Item::where($where)->paginate());
        }
    }

    public function my()
    {
        $userId = auth()->id();
        return new ItemsCollection(Item::whereHas('buyers', function ($q) use ($userId) {
            $q->where('buyer_id', $userId);
        })->paginate());
    }

    public function show(Item $item)
    {
        return response()->json(new ItemResource($item), 200);
    }

    public function upload(ItemUploadRequest $request)
    {
        $data = $request->validated();
        $data['uploader_id'] = auth()->guard('api')->id();
        $data['status'] = 'PENDING_REVIEW';
        Item::create($data);
        return response()->json(['message' => 'Thanks. Your item is pending review.'], 201);
    }

    public function buy(ItemBuyRequest $request, Item $item)
    {
        $user = $request->user();
        if (UserBoughtItem::where([
            'buyer_id' => $user->id,
            'item_id' => $item->id,
        ])->first()) {
            return response()->json(['message' => 'You already own this item'], 400);
        }

        $account = $this->getUserMoneyAccount($user);
        if ($account->balance >= $item->price) {

            $this->addInternalTransaction($user, 'Item', $item->id, $item->price);

            $userBought = UserBoughtItem::create([
                'buyer_id' => $user->id,
                'item_id' => $item->id,
                'paid' => $item->price,
            ]);
            $account->update([
                'balance' => $account->balance - $userBought->paid,
            ]);
            return response()->json([
                'message' => 'Bought the item successfully for ' . $userBought->paid . ' EGP.',
            ], 201);
        }
        return response()->json([
            'message' => 'Sorry, You do not have enough balance to buy it',
        ], 400);
    }

    public function buyCallback(ItemBuyCallbackRequest $request)
    {
        if ($request['merchant_id'] != config('app.merchant_id')) {
            return response()->json(['message' => 'Wrong Merchant.'], 400);
        }

        $transaction = Transaction::where(['reference' => $request['reference']])->first();
        if (!$transaction) {
            return response()->json(['message' => 'Reference not found.'], 404);
        }

        if ($request['status'] == 'PAID') {
            $transaction->update(['paid_at' => Carbon::now()]);
            UserBoughtItem::create([
                'student_id' => $transaction['user_id'],
                'item_id' => $transaction['item_id'],
                'paid' => $transaction['amount'],
            ]);
        }
        if ($request['status'] == 'EXPIRED') {
            $transaction->update(['expired_at' => Carbon::now()]);
        }
        return response()->json(['message' => 'Updated Successfully.'], 202);
    }
}

app/Http/Controllers/Dashboard/CreatorStudentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\CreatorStudentStoreRequest;
use App\Http\Requests\Dashboard\CreatorStudentUpdateRequest;
use App\Models\City;
use App\Models\CreatorStudentRequest;
use App\Models\Faculty;
use App\Models\Governorate;
use App\Models\University;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\CreatorStudentsExport;

class CreatorStudentController extends Controller
{
    public function requests()
    {
        return view('dashboard.creator-students.requests')
            ->with('creatorStudentRequests', CreatorStudentRequest::where('status', 'PENDING')
                ->orderBy('id', 'desc')->paginate())
            ->with('total', CreatorStudentRequest::where('status', 'PENDING')->count());
    }

    public function index(Request $request)
    {
        $search_q = '';
        if ($request->has('search_q')) {
            $search_q = $request['search_q'];
        }

        $where = [];
        if ($request->has('majorId')) {
            $where['major_id'] = $request['majorId'];
        }
        if ($request->has('facultyId')) {
            $where['faculty_id'] = $request['facultyId'];
        }
        if ($request->has('universityId')) {
            $where['university_id'] = $request['universityId'];
        }
        if ($request->has('governorateId')) {
            $where['governorate_id'] = $request['governorateId'];
        }
        $creatorStudents = User::role('UNIVERSITY_CREATOR_STUDENT')
            ->where($where)
            ->where('name', 'LIKE', '%' . $search_q . '%')
            ->orderBy('id', 'DESC')
            ->paginate();

        return view('dashboard.creator-students.index')
            ->with('creatorStudents', $creatorStudents)
            ->with('total', $creatorStudents->total())
            ->with('indexUrl', route('dashboard.creator-students.index'));
    }

    public function export(Request $request)
    {
        $fileName = 'creatorstudents' . time();
        return Excel::download(new CreatorStudentsExport($this->buildingWhereQuery($request->all())), $fileName . '.xlsx');
    }

    private function buildingWhereQuery($dataArray)
    {
        $where = [];
        if (array_key_exists('majorId', $dataArray)) {
            $where['major_id'] = $dataArray['majorId'];
        }
        if (array_key_exists('facultyId', $dataArray)) {
            $where['faculty_id'] = $dataArray['facultyId'];
        }
        if (array_key_exists('universityId', $dataArray)) {
            $where['university_id'] = $dataArray['universityId'];
        }
        if (array_key_exists('governorateId', $dataArray)) {
            $where['governorate_id'] = $dataArray['governorateId'];
        }
        return $where;
    }

    public function create()
    {
        $governorates = Governorate::where(['country_id' => 1])->get();
        $universities = count($governorates) > 0 ? University::where(['governorate_id' => $governorates->first()->id])->get() : [];
        $faculties = count($universities) > 0 ? Faculty::where(['university_id' => $universities->first()->id])->get() : [];
        return view('dashboard.creator-students.create')
            ->with('governorates', $governorates)
            ->with('universities', $universities)
            ->with('faculties', $faculties);
    }

    public function store(CreatorStudentStoreRequest $request)
    {
        $creatorStudent = User::create($request->validated());
        $role = Role::findByName('UNIVERSITY_CREATOR_STUDENT');
        if ($role) {
            $creatorStudent->syncRoles(['UNIVERSITY_CREATOR_STUDENT']);
        }
        return redirect()->route('dashboard.creator-students.index')
            ->with('message', trans('crud.success.store'))->with('class', 'alert-success');
    }

    public function show(User $creatorStudent)
    {
        return redirect()->route('dashboard.creator-students.edit', $creatorStudent['id']);
    }

    public function edit(User $creatorStudent)
    {
        $cities = City::where(['country_id' => 1])->get();
        $universities = count($cities) > 0 ? University::where(['city_id' => $creatorStudent->city_id])->get() : [];
        $faculties = count($universities) > 0 ? Faculty::where(['university_id' => $creatorStudent->university_id])->get() : [];
        return view('dashboard.creator-students.edit')
            ->with('creatorStudent', $creatorStudent)
            ->with('cities', $cities)
            ->with('universities', $universities)
            ->with('faculties', $faculties);
    }

    public function update(CreatorStudentUpdateRequest $request, User $creatorStudent)
    {
        $data = $request->only(['city_id', 'university_id', 'name', 'email']);
        if ($request->has('password')) {
            $data['password'] = $request['password'];
        }
        $creatorStudent->update($data);
        return redirect()->route('dashboard.creator-students.index')
            ->with('message', trans('crud.success.update'))->with('class', 'alert-success');
    }

    public function destroy(User $creatorStudent)
    {
        $creatorStudent->delete();
        return response()->json(['message' => 'Deleted Successfully'], 200);
    }
}

resources/views/creator-student/items/edit.blade.php
@extends('layouts.creator-student-master')

@section('title','Edit Item '.$item->name)

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Edit Item</h1>
        </div>
        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    @include('creator-student.common._alert_message')
                    @include('creator-student.common._alert_validation_errors')
                    <div class="card">
                        <div class="card-header">
                            <h4>Update Item</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('creator-student.items.update',$item->id) }}"
                                  enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Item Name</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="text" name="name" value="{{old('name',$item->name)}}"
                                               class="form-control @error('name') is-invalid @enderror">
                                        @error('name')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('name') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Type</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control @error('type') is-invalid @enderror"
                                                name="type">
                                            <option {{$item->type=='BOOK'?' selected':''}}>BOOK</option>
                                            <option {{$item->type=='SHEET'?' selected':''}}>SHEET</option>
                                            <option {{$item->type=='SUMMARY'?' selected':''}}>SUMMARY</option>
                                            <option {{$item->type=='OTHER'?' selected':''}}>OTHER</option>
                                        </select>
                                        @error('type')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('type') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Level</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control @error('level') is-invalid @enderror"
                                                name="level">
                                            @foreach($levels as $level)
                                                <option {{$item->level==$level->label?' selected':''}}>{{$level->label}}</option>
                                            @endforeach
                                        </select>
                                        @error('level')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('level') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">University Subject</label>
                                    <div class="col-sm-12 col-md-7">
                                        <select class="form-control @error('university_subject_id') is-invalid @enderror"
                                                name="university_subject_id">
                                            @foreach($universitySubjects as $universitySubject)
                                                <option {{ $item->university_subject_id==$universitySubject->id?' selected':'' }}
                                                        value="{{$universitySubject->id}}">{{$universitySubject->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('university_subject_id')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('university_subject_id') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">New File</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="file" name="file"
                                               class="form-control @error('file') is-invalid @enderror">
                                        @error('file')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('file') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    @if($item->image)
                                        <div class="col-12">
                                            <div class="col text-center">
                                                <img src="{{ $item->image_link }}" alt="image"
                                                     class="avatar-presence mr-1" width="80">
                                            </div>
                                        </div>
                                    @endif
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="file" name="image"
                                               class="form-control @error('image') is-invalid @enderror">
                                        @error('image')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('image') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Price</label>
                                    <div class="col-sm-12 col-md-7">
                                        <input type="number" step="0.01" name="price" value="{{old('price',$item->price)}}"
                                               class="form-control @error('price') is-invalid @enderror">
                                        @error('price')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('price') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"
                                           for="description">Description</label>
                                    <div class="col-sm-12 col-md-7">
                                        <textarea class="form-control @error('description') is-invalid @enderror"
                                                  id="description" name="description"
                                                  rows="4">{{old('description',$item->description)}}</textarea>
                                        @error('description')
                                        <div class="invalid-feedback">
                                            <p>{{ $errors->first('description') }}</p>
                                        </div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                    <div class="col-sm-12 col-md-7">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                        <a href="{{route('creator-student.items.index')}}" class="btn btn-danger">Cancel</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection

resources/views/creator-student/items/index.blade.php
@extends('layouts.creator-student-master')

@section('title','Manage Items')

@section('content')
    <section class="section">
        <div class="section-header"><h1>Manage Items</h1></div>
        @include('creator-student.common._alert_message')
        <div class="section-body">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Items <span>({{ $total }})</span></h4>
                            <div class="card-header-action">
                                <a href="{{route('creator-student.items.create')}}"
                                   class="btn btn-primary">Add <i class="fas fa-plus"></i></a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive table-invoice">
                                @if(count($items)>0)
                                    <table class="table table-striped">
                                        <tbody>
                                        <tr>
                                            <th>Level</th>
                                            <th>Name</th>
                                            <th>Type</th>
                                            <th>Creator</th>
                                            <th>Price</th>
                                            <th>Version</th>
                                            <th></th>
                                        </tr>
                                        @foreach($items as $item)
                                            <tr>
                                                <td>{{ $item->level }}</td>
                                                <td>{{ $item->name }}</td>
                                                <td>{{ $item->type }}</td>
                                                <td>{{ $item->creator->name }}</td>
                                                <td>{{ $item->price }}</td>
                                                <td>{{ $item->version }}</td>

                                                <td class="text-right">
                                                    <a href="{{route('creator-student.items.show',$item->id)}}"
                                                       class="btn btn-success">
                                                        <i class="fa fa-eye"></i>
                                                    </a>

                                                    <a href="{{route('creator-student.items.edit',$item->id)}}"
                                                       class="btn btn-primary">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    <button class="btn btn-danger delete"
                                                            data-id="{{$item->id}}" type="button">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                @else
                                    <div class="text-center p-3 text-muted">
                                        <h5>No Results</h5>
                                        <p>Looks like you have not added any items yet!</p>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                    @if(count($items)>0)
                        <div class="text-center">
                            {{$items->links()}}
                        </div>
                    @endif
                </div>
            </div>

        </div>
    </section>
@endsection

@section('scripts')
    @include('creator-student.common._modal_delete')
@endsection